// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB_pTXoz0yDh1MGnHCiwIkp07a3y8MmjHc',
    appId: '1:822418720763:web:602d1e6e12037dce242d5e',
    messagingSenderId: '822418720763',
    projectId: 'lagoinhamusic-dc9f6',
    authDomain: 'lagoinhamusic-dc9f6.firebaseapp.com',
    storageBucket: 'lagoinhamusic-dc9f6.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAzRKOd6SU3xTzyA4Tqnw1zjV3d_ruaeeo',
    appId: '1:822418720763:android:05a82a2f49c08c7e242d5e',
    messagingSenderId: '822418720763',
    projectId: 'lagoinhamusic-dc9f6',
    storageBucket: 'lagoinhamusic-dc9f6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCD_caFpcLwSNDYlz7nvJM90yT9CZwSTJA',
    appId: '1:822418720763:ios:d48ec3de665202a6242d5e',
    messagingSenderId: '822418720763',
    projectId: 'lagoinhamusic-dc9f6',
    storageBucket: 'lagoinhamusic-dc9f6.appspot.com',
    iosBundleId: 'com.example.lagoinhaMusic',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCD_caFpcLwSNDYlz7nvJM90yT9CZwSTJA',
    appId: '1:822418720763:ios:d48ec3de665202a6242d5e',
    messagingSenderId: '822418720763',
    projectId: 'lagoinhamusic-dc9f6',
    storageBucket: 'lagoinhamusic-dc9f6.appspot.com',
    iosBundleId: 'com.example.lagoinhaMusic',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB_pTXoz0yDh1MGnHCiwIkp07a3y8MmjHc',
    appId: '1:822418720763:web:1af53f574e5190a1242d5e',
    messagingSenderId: '822418720763',
    projectId: 'lagoinhamusic-dc9f6',
    authDomain: 'lagoinhamusic-dc9f6.firebaseapp.com',
    storageBucket: 'lagoinhamusic-dc9f6.appspot.com',
  );
}
